const SERVERLESS = {
  REGION: process.env.SERVERLESS_REGION,
};

const COGNITO = {
  CLIENT_ID: process.env.COGNITO_CLIENT_ID,
  USER_POOL_ID: process.env.COGNITO_USER_POOL_ID,
  USER_POOL_ARN: process.env.COGNITO_USER_POOL_ARN,
};

export const CONFIG = { SERVERLESS, COGNITO };
