export const waitlingListMock = [
  {
    name: 'Sobhraj',
    lastName: null,
    email: 'blahblah1@hotmail.com',
    phone: 629917152,
    referralCode: 'MXM3D',
    referrerCode: null,
  },
  {
    name: 'Mohammed',
    lastName: null,
    email: 'blahblah2@hotmail.com',
    phone: 618690405,
    referralCode: 'TEXFO',
    referrerCode: null,
  },
  {
    name: 'Sammie',
    lastName: null,
    email: 'blahblah3@hotmail.com',
    phone: 636023358,
    referralCode: '7WOMT',
    referrerCode: null,
  },
  {
    name: 'Chafai',
    lastName: null,
    email: 'blahblah4@hotmail.com',
    phone: 611335451,
    referralCode: 'NHTY7',
    referrerCode: null,
  },
  {
    name: 'Merdan',
    lastName: null,
    email: 'blahblah5@hotmail.com',
    phone: 31630405097,
    referralCode: '0HV8H',
    referrerCode: null,
  },
  {
    name: 'Nasir',
    lastName: null,
    email: 'blahblah6@hotmail.com',
    phone: 31636415500,
    referralCode: 'SNJ6L',
    referrerCode: null,
  },
];
